### ISSUE TITLE
documentation improvement suggestion, section: Backing up and restoring PVC data for file and block storage

### ISSUE THREAD

**Issue by gthackra** [ibm-cloud-docs/containers#2588]
step 7 of this section
https://github.com/ibm-cloud-docs/containers/blob/master/storage-utilities.md#backing-up-and-restoring-pvc-data-for-file-and-block-storage

contains yaml that our team have had issues with, they found the following yaml better

```yaml
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: restore
    labels:
    app: nginx
  spec:
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
          - image: nginx
            name: nginx
            volumeMounts:
            - name: my-volume # Example: my_volume
              mountPath: /test # Example: /test
        volumes:
        - name: my-volume # Example: my_volume
          persistentVolumeClaim:
            claimName: my-actual-pvc-name # Example: my_pvc
```
