### ISSUE TITLE
Sample Ingress indentation is incorrect.

### ISSUE THREAD

**Issue by abhishektuf** [ibm-cloud-docs/containers#2589]
The indentation of given sample Ingress resource for Kubernetes version 1.19 or later on page https://cloud.ibm.com/docs/containers?topic=containers-ingress-types#alb-comm-create  under step 2 is incorrect. The correct one should be like below.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: community-ingress-resource
  annotations:
    kubernetes.io/ingress.class: "public-iks-k8s-nginx"
spec:
  tls:
  - hosts: 
    - HOSTNAME
    secretName: SECRET_NAME
  rules:
  - host: HOSTNAME
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: nginx-auth
            port:
              number: 80
```
