### ISSUE TITLE
indentation off in pvc.yaml

### ISSUE THREAD

**Issue by Dogba-0104** [ibm-cloud-docs/containers#2607]
hi team can you fix the indentation in the sample pvc yaml adding corrected version
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: silver-pvc
  labels:
      billingType: hourly
      region: eu-central
      zone: mil01
spec:
  accessModes:
   - ReadWriteMany
  resources:
      requests:
        storage: 24Gi
  storageClassName: ibmc-file-silver
```
