### ISSUE TITLE
Error in PV resource "Using an existing Block Storage for VPC instance"

### ISSUE THREAD

**Issue by massimocaprinali** [ibm-cloud-docs/containers#2628]
In section **Using an existing Block Storage for VPC instance** _(topic=containers-vpc-block#vpc-block-static)_ the code of Persistent Volume resource is wrong.

```yaml
nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        ...
        - key: failure-domain.beta.kubernetes.io/hostname
          operator: In
          values:
          - <worker_node_primary_IP>
 ```

should be 

```yaml
nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        ...
        - key: kubernetes.io/hostname
          operator: In
          values:
          - <worker_node_primary_IP>
 ```

Otherwise there is an error when mounting PVC
