### ISSUE TITLE
ingress sample yaml indentation wrong

### ISSUE THREAD

**Issue by Dogba-0104** [ibm-cloud-docs/containers#2643]
Hi team, 
The sample code for the ingress yaml indentation is off
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: community-ingress-resource
  annotations:
    kubernetes.io/ingress.class: "private-iks-k8s-nginx"
spec:
  rules:
  - host: <hostname>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: <servicename>
            port:
              number: 80
```

is sample i used (omitting tls for my use case)
